void root()
{
//=========Macro generated from canvas: c1/c1
//=========  (Sun Jul 30 09:54:03 2023) by ROOT version 6.20/08
   TCanvas *c1 = new TCanvas("c1", "c1",67,57,700,500);
   c1->SetHighLightColor(2);
   c1->Range(-2.5,-15,2.5,135);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1D *Mres_dnn__1 = new TH1D("Mres_dnn__1","",50,-2,2);
   Mres_dnn__1->SetBinContent(27,1);
   Mres_dnn__1->SetBinContent(28,5);
   Mres_dnn__1->SetBinContent(29,16);
   Mres_dnn__1->SetBinContent(30,48);
   Mres_dnn__1->SetBinContent(31,135);
   Mres_dnn__1->SetBinContent(32,163);
   Mres_dnn__1->SetBinContent(33,96);
   Mres_dnn__1->SetBinContent(34,21);
   Mres_dnn__1->SetBinContent(35,6);
   Mres_dnn__1->SetBinContent(36,3);
   Mres_dnn__1->SetBinContent(37,1);
   Mres_dnn__1->SetBinContent(38,3);
   Mres_dnn__1->SetBinContent(40,2);
   Mres_dnn__1->SetBinContent(51,1);
   Mres_dnn__1->SetMinimum(0);
   Mres_dnn__1->SetMaximum(120);
   Mres_dnn__1->SetEntries(501);
   Mres_dnn__1->SetDirectory(0);
   Mres_dnn__1->SetStats(0);
   Mres_dnn__1->SetLineColor(2);
   Mres_dnn__1->SetLineWidth(4);
   Mres_dnn__1->GetXaxis()->SetTitle("M_{reco} - M_{gen}/M_{gen}");
   Mres_dnn__1->GetXaxis()->SetLabelFont(42);
   Mres_dnn__1->GetXaxis()->SetTitleOffset(1);
   Mres_dnn__1->GetXaxis()->SetTitleFont(42);
   Mres_dnn__1->GetYaxis()->SetLabelFont(42);
   Mres_dnn__1->GetYaxis()->SetTitleFont(42);
   Mres_dnn__1->GetZaxis()->SetLabelFont(42);
   Mres_dnn__1->GetZaxis()->SetTitleOffset(1);
   Mres_dnn__1->GetZaxis()->SetTitleFont(42);
   Mres_dnn__1->Draw("histo");
   
   TH1D *Mres_svfit__2 = new TH1D("Mres_svfit__2","",50,-2,2);
   Mres_svfit__2->SetBinContent(14,10);
   Mres_svfit__2->SetBinContent(15,5);
   Mres_svfit__2->SetBinContent(16,9);
   Mres_svfit__2->SetBinContent(17,12);
   Mres_svfit__2->SetBinContent(18,17);
   Mres_svfit__2->SetBinContent(19,10);
   Mres_svfit__2->SetBinContent(20,32);
   Mres_svfit__2->SetBinContent(21,34);
   Mres_svfit__2->SetBinContent(22,44);
   Mres_svfit__2->SetBinContent(23,63);
   Mres_svfit__2->SetBinContent(24,76);
   Mres_svfit__2->SetBinContent(25,71);
   Mres_svfit__2->SetBinContent(26,73);
   Mres_svfit__2->SetBinContent(27,31);
   Mres_svfit__2->SetBinContent(28,9);
   Mres_svfit__2->SetBinContent(29,1);
   Mres_svfit__2->SetBinContent(30,1);
   Mres_svfit__2->SetBinContent(31,2);
   Mres_svfit__2->SetBinContent(33,1);
   Mres_svfit__2->SetEntries(501);
   Mres_svfit__2->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   Mres_svfit__2->SetLineColor(ci);
   Mres_svfit__2->SetLineWidth(4);
   Mres_svfit__2->GetXaxis()->SetLabelFont(42);
   Mres_svfit__2->GetXaxis()->SetTitleOffset(1);
   Mres_svfit__2->GetXaxis()->SetTitleFont(42);
   Mres_svfit__2->GetYaxis()->SetLabelFont(42);
   Mres_svfit__2->GetYaxis()->SetTitleFont(42);
   Mres_svfit__2->GetZaxis()->SetLabelFont(42);
   Mres_svfit__2->GetZaxis()->SetTitleOffset(1);
   Mres_svfit__2->GetZaxis()->SetTitleFont(42);
   Mres_svfit__2->Draw("histosame");
   TLatex *   tex = new TLatex(0.7,89.06,"#bf{DNN}");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,79,"rms : 0.1185");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,69,"mean: 0.5058");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,50.06,"#bf{SvFit}");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,40.06,"rms : 0.2554");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,30.06,"mean: -0.1925");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.13,0.67,0.45,0.87,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","#bf{DNN vs SVfit} ","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextAlign(22);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Mres_dnn","dnn background","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Mres_svfit","SvFit background","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
