void Mres_zp()
{
//=========Macro generated from canvas: c1/
//=========  (Mon Nov 27 18:39:12 2023) by ROOT version 6.24/06
   TCanvas *c1 = new TCanvas("c1", "",0,53,800,800);
   c1->SetHighLightColor(2);
   c1->Range(-2.5,-22.5,2.5,202.5);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1D *Mres_dnn__1 = new TH1D("Mres_dnn__1","",40,-2,2);
   Mres_dnn__1->SetBinContent(18,27);
   Mres_dnn__1->SetBinContent(19,51);
   Mres_dnn__1->SetBinContent(20,99);
   Mres_dnn__1->SetBinContent(21,90);
   Mres_dnn__1->SetBinContent(22,83);
   Mres_dnn__1->SetBinContent(23,56);
   Mres_dnn__1->SetBinContent(24,30);
   Mres_dnn__1->SetBinContent(25,7);
   Mres_dnn__1->SetBinContent(26,7);
   Mres_dnn__1->SetBinContent(27,1);
   Mres_dnn__1->SetBinContent(28,2);
   Mres_dnn__1->SetMinimum(0);
   Mres_dnn__1->SetMaximum(180);
   Mres_dnn__1->SetEntries(453);
   Mres_dnn__1->SetDirectory(0);
   Mres_dnn__1->SetStats(0);
   Mres_dnn__1->SetLineColor(4);
   Mres_dnn__1->SetLineWidth(5);
   Mres_dnn__1->GetXaxis()->SetTitle("(M_{reco} - M_{gen})/M_{gen}");
   Mres_dnn__1->GetXaxis()->SetLabelFont(42);
   Mres_dnn__1->GetXaxis()->SetTitleOffset(1);
   Mres_dnn__1->GetXaxis()->SetTitleFont(42);
   Mres_dnn__1->GetYaxis()->SetLabelFont(42);
   Mres_dnn__1->GetYaxis()->SetTitleFont(42);
   Mres_dnn__1->GetZaxis()->SetLabelFont(42);
   Mres_dnn__1->GetZaxis()->SetTitleOffset(1);
   Mres_dnn__1->GetZaxis()->SetTitleFont(42);
   Mres_dnn__1->Draw("histo");
   
   TH1D *Mres_mAN__2 = new TH1D("Mres_mAN__2","",40,-2,2);
   Mres_mAN__2->SetBinContent(11,2);
   Mres_mAN__2->SetBinContent(17,21);
   Mres_mAN__2->SetBinContent(18,66);
   Mres_mAN__2->SetBinContent(19,68);
   Mres_mAN__2->SetBinContent(20,95);
   Mres_mAN__2->SetBinContent(21,94);
   Mres_mAN__2->SetBinContent(22,80);
   Mres_mAN__2->SetBinContent(23,52);
   Mres_mAN__2->SetBinContent(24,17);
   Mres_mAN__2->SetBinContent(25,2);
   Mres_mAN__2->SetBinContent(26,3);
   Mres_mAN__2->SetEntries(500);
   Mres_mAN__2->SetDirectory(0);
   Mres_mAN__2->SetLineColor(2);
   Mres_mAN__2->SetLineWidth(5);
   Mres_mAN__2->GetXaxis()->SetLabelFont(42);
   Mres_mAN__2->GetXaxis()->SetTitleOffset(1);
   Mres_mAN__2->GetXaxis()->SetTitleFont(42);
   Mres_mAN__2->GetYaxis()->SetLabelFont(42);
   Mres_mAN__2->GetYaxis()->SetTitleFont(42);
   Mres_mAN__2->GetZaxis()->SetLabelFont(42);
   Mres_mAN__2->GetZaxis()->SetTitleOffset(1);
   Mres_mAN__2->GetZaxis()->SetTitleFont(42);
   Mres_mAN__2->Draw("histosame");
   TLatex *   tex = new TLatex(0.808271,122.76,"#bf{DNN}");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.808271,114.395,"rms : 0.18");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.808271,107,"mean: 0.065");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.808271,97.8629,"#bf{mAN}");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.808271,89.879,"rms : 0.1933");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.808271,81.8952,"mean: -0.0063");
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.13,0.67,0.45,0.87,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","#bf{DNN vs mAN} ","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextAlign(22);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Mres_dnn","dnn 3TeV","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Mres_mAN","mAN 3TeV","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
